---
title: "Session 4"
date: "2017-09-18, Monday, 3pm"
output: html_document
---

Potential outline for the coming weeks. The next quokka meeting is on the 18th September 

1. Rstats News: "Any news in R that's interesting?"

- Rstudio has launched [an online community](https://community.rstudio.com/) to support tidyverse, shiny, package development, and rstudio related topics:
  - https://blog.rstudio.com/2017/09/14/rstudio-community/
  - https://twitter.com/hadleywickham/status/908337225347280897
  - Kickstarting their 

- Cool blog posts:
  - [Edwin Thoen: how tidy eval builds on base R](https://edwinth.github.io/blog/nse/)
  - [Mara Averick's roundup of tidyeval resources](http://maraaverick.rbind.io/2017/08/tidyeval-resource-roundup/)
  - [RStudio v1.1 - the little things](https://blog.rstudio.com/2017/09/13/rstudio-v1.1---the-little-things/)
  - [Data visualisation for the social sciences](http://socviz.co/)
  - [plotly 4.7.1 on CRAN](https://moderndata.plot.ly/plotly-4-7-1-now-on-cran/)
  - [Discussion/roundup on unifying packages to help users access R repos](https://nashjc.wordpress.com/2017/09/03/unifying-packages-to-help-users-access-r-repositories/)
  - [rOpenSci post about their onboarding process](https://ropensci.org/blog/blog/2017/09/11/software-review-update)
  - [rOpenSci Spelling check package](https://ropensci.org/blog/technotes/2017/09/07/spelling-release)
  - [rOpenSci code review](https://ropensci.org/blog/blog/2017/09/01/nf-softwarereview)
  - [Alternative Representations for R Objects](https://svn.r-project.org/R/branches/ALTREP/ALTREP.html)

- Any R packages we've released?

2. Oh God, Help.

?

3. Reading group: Metaprogramming section of Advanced R

- http://adv-r.hadley.nz/nse.html#capturing-expressions
- Chapter 17.1 discussion:
  - Read through 17.1 and do exercises.
  - Discuss answers and thoughts
  - Discuss future paths (how much and how long to read?)

