---
title: "Session-5-Agenda"
output: html_document
---

# Meeting on 25th September 3pm.

## 1. Rstats News: "Any news in R that's interesting?"

- [Rweekly](https://rweekly.org/) - a great resource
- [lime: explaining black-box model predictions](http://www.data-imaginist.com/2017/Announcing-lime/)
- [rice, command line R interface](https://github.com/randy3k/rice)
- [linemap - ridge/joy plots on maps](https://github.com/rCarto/linemap)
- [RStudio webinars](https://www.rstudio.com/resources/webinars/) - full of nuggets of wisdom
- [Yihui's blog](https://yihui.name/en/) - not on r-bloggers anymore, but he's been blogging a lot lately, probably because [blogdown]() is so easy to use.
- [rbind](https://github.com/rbind)

- [rivis](https://github.com/ropenscilabs/rivis)

- RStudio community discussion on ggvis

- [RStudio addin for editing dataframes](https://github.com/cardiomoon/editData) - not sure if terrifying.

- Quote (ripped from RWeekly)

> Next time someone says "excel is the worst" be more helpful and say this ... #rstats #EARLConf2017 pic.twitter.com/2PHKRPteAg ( twitter.com ): — Alice Data (@alice_data) September 14, 2017 ( twitter.com ) 

- Cool blog posts
- R core changes?
- Any R packages we've released?

## 2. R-Help: A friendly place to discuss topics you need some help/direction with.

## 3. Reading group: Metaprogramming section of Advanced R

- Hadley appears to be actively developing this book, which has resulted in a new, but I think better chapter order.
-
- We are going to start reading through chapter 18 - expressions: https://adv-r.hadley.nz/expressions, the whole chapter (18.1 - 18.5)
- Do the exercises
- Discuss answers and thoughts

# Future weeks

- We will then move on to Chapter 20, 21, and 22 - as it currently looks like chapter 19 "Tidy Evaluation" is not completed.

- Following this, we will move onto the chapter on Debugging, condition handling, and defensive programming: https://adv-r.hadley.nz/debugging
